# preforms CI builds using compose.py from
# https://github.com/CleverRaven/Cataclysm-DDA
#
# This action is triggerd by any PR against the master branch as well
# as on any push to the master branch itself
name: Cuteclysm composer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl python3 python3-pip libvips42

        # re-installing libvips; caching it won't set it up the way we need it
        # still cache it because we'll make it work somehow
      - run: sudo apt-get install libvips42
      - run: pip3 install pyvips

      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build
        id: build
        run: |
          wget -q https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/master/tools/gfx_tools/compose.py \
          || echo "Error: Failed to get compose.py"

          mkdir build
          python3 compose.py --use-all --feedback CONCISE --loglevel INFO . build

          artifact_name=Cuteclysm-dev-git-${GITHUB_SHA::7}

          mkdir "$artifact_name"

          cp -r build/*     "$artifact_name"
          mv ./tileset.txt  "$artifact_name"
          mv ./fallback.png "$artifact_name"

          echo "ARTIFACT-NAME=$artifact_name" >> $GITHUB_OUTPUT

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.ARTIFACT-NAME }}
          path: ${{ steps.build.outputs.ARTIFACT-NAME }}
